pattern_rules:
  - type: name
    patterns: ["证券", "金融", "环境","水泥"]
  - type: themeF
    patterns: ["证券","金融","白酒","环境", "光伏", "外贸","水泥"]
blacklist_codes:
  - "sz002506"
  - "sz002153"
  - "sh600184"
  - "sz002492"
  - "sz002715"
  - "sz002548"
  - "sh603698"
  - "sz002949"
  - "sh600797"
  - "sz002266"
  - "sz000980" #傻逼众泰，拉黑不谢
  - "sh600635" #大众公用，高位横盘未突破
  - "sh603800" #洪田股份，25年两次大额亏损，22-24年六次亏损，不符合我这个策略。盈利的情况基本都是会跌破首板价格。
  - "sh601615" #明阳智能，光伏的先不买了
  - "sz002977" #天箭科技，两连跌停